"""Entry point for analyze.analysis_forecasts.

Run via ``python -m analyze.analysis_forecasts``.

Monthly per-security forecast analysis in the ``analysis_forecasts``
schema (see database/sql/analysis/analysis_forecasts/):

  - mov_rsi: per (sec_type, code, stat_month, rsi_window, side, pct,
    is_market_hyped) RSI extreme-percentile bucket definitions (RSI
    values join from analysis.mov_ave_rsi).

  - mov_std: per (sec_type, code, stat_month, ma_window, k, side,
    is_market_hyped) Bollinger-breach bucket definitions (motivation:
    breach magnitude mean_excess_close / mean_excess_max /
    max_excess_max; band inputs join from
    analysis.mov_ave_spreads_detail / stats.*_tech_stats).

  - forecast_results: the result data (mean forward changes at
    next/5d/20d/60d horizons; close-based max/min forward changes and
    the within-window close swing amplitude max_low_change_ratio at the
    5d/20d/60d horizons; per-horizon >1% reversal probabilities),
    keyed by forecast_id; every mov_rsi / mov_std row links 1:1 to its
    result row via forecast_id.

Pipeline per sec_type (index / etf / stock):
  1. Fetch active-universe codes (recent-data pre-filter).
  2. Incremental: detect stat_months missing from each mov_* table
     (month-level DISTINCT stat_month check — completed-month snapshots
     are immutable, so no recomputation of present months). ``--force``
     deletes the sec_type's mov_* rows AND their linked forecast_results
     rows, then recomputes every target month.
  3. Fetch the joined long input frame (price / high / low / ma / rsi /
     std columns; date >= earliest needed window start), the compact
     market-hype EPISODES list, and compute per-code forward changes
     (1/5/20/60 trading days).
  4. Scatter to (date × code) wide matrices + the market-hype flag
     matrix and run the vectorized monthly aggregation engines
     (compute_rsi / compute_std), writing month-major batches:
     forecast_id allocated from the identity sequence, then COPY into
     forecast_results + the mov_* table in ONE transaction per month
     (no pre-clear DELETEs — months are only written when missing or
     after force deletion; atomicity keeps the 1:1 link crash-safe).
  5. Upsert analysis.analysis_identity.

Row emission contract: buckets with day_count = 0 emit NO row (a code
without valid RSI / MA+std in a window simply has no buckets that month).
"""
from __future__ import annotations


# resource pre-check -- exit early when sys/GPU memory is insufficient
from _common.pre_check import pre_check

pre_check()
import argparse
import asyncio
import os
import sys
import time
from datetime import timedelta

# Ensure project root is on sys.path so ``_common`` is importable when run
# directly via ``python -m analyze.analysis_forecasts`` or as a script.
sys.path.insert(
    0,
    os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ),
)

from _common.build_commons import (  # noqa: E402
    setup_utf8_stdout,
    get_db_connection_async,
    print_build_header,
    print_wall_time,
    add_force_arg,
)
from _common.db_commons import (  # noqa: E402
    copy_insert_async,
)

setup_utf8_stdout()

# cudf.pandas activation — must run before pandas first import
from _common.df_utils._activate import activate  # noqa: E402
activate()

from analyze._common import upsert_analysis_identity  # noqa: E402
from analyze.analysis_forecasts.config import (  # noqa: E402
    TABLE_FORECAST,
    TABLE_MOV_RSI,
    TABLE_MOV_STD,
    ANALYSIS_NAME_RSI,
    ANALYSIS_NAME_STD,
    DESCRIPTION_RSI,
    DESCRIPTION_STD,
    SEC_TYPES,
    MOV_RSI_COLUMNS,
    MOV_STD_COLUMNS,
    RSI_WINDOWS,
    MA_WINDOWS,
    N_MONTHS,
    WINDOW_YEARS,
)
from analyze.analysis_forecasts.fetch import (  # noqa: E402
    fetch_active_codes,
    fetch_analysis_inputs,
    fetch_first_dates,
    fetch_hyped_episodes,
    add_forward_changes,
)
from analyze.analysis_forecasts.wide import (  # noqa: E402
    build_month_specs,
    build_grid,
    first_ords_from_dates,
    build_hype_matrix,
    scatter_column,
    build_change_matrices,
    month_row_windows,
    split_forecast_rows,
    MonthSpec,
    _shift_years,
)
from analyze.analysis_forecasts.compute_rsi import compute_rsi_results  # noqa: E402
from analyze.analysis_forecasts.compute_std import compute_std_results  # noqa: E402


# Max rows per COPY chunk (a full stock-universe month of rsi buckets is
# <= 64 × ~5,400 ≈ 345K rows; chunk to bound peak dict memory).
_WRITE_CHUNK = 100_000

# Identity sequence backing forecast_results.forecast_id (GENERATED BY
# DEFAULT AS IDENTITY → <table>_<column>_seq). Allocated in blocks so a
# whole chunk of linked mov/result rows is written with one round-trip.
_FORECAST_ID_SEQ = "analysis_forecasts.forecast_results_forecast_id_seq"


# ---------------------------------------------------------------------------
#  Incremental month detection
# ---------------------------------------------------------------------------

async def _missing_stat_months(
    conn,
    table: str,
    sec_type: str,
    specs: list[MonthSpec],
) -> list[MonthSpec]:
    """Target spec months not yet present in ``table`` for this sec_type.

    Month-level check (DISTINCT stat_month): completed-month snapshots are
    immutable — closes / RSI / MA / std inside a window are historical
    facts and the window is anchored at the month-end, so present months
    are never recomputed. Codes listed AFTER a month was computed are
    backfilled by --force.
    """
    rows = await conn.fetch(
        f"SELECT DISTINCT stat_month FROM {table} WHERE sec_type = $1",
        sec_type,
    )
    present = {r["stat_month"] for r in rows}
    return [s for s in specs if s.stat_month not in present]


# ---------------------------------------------------------------------------
#  Force deletion (mov rows + their linked forecast_results rows)
# ---------------------------------------------------------------------------

async def _delete_sec_type(conn, sec_type: str) -> None:
    """Delete a sec_type's mov_rsi / mov_std rows and the
    forecast_results rows they link to."""
    for mov_table in (TABLE_MOV_RSI, TABLE_MOV_STD):
        await conn.execute(
            f"DELETE FROM {TABLE_FORECAST} f USING {mov_table} m "
            f"WHERE m.forecast_id = f.forecast_id AND m.sec_type = $1",
            sec_type,
        )
        await conn.execute(
            f"DELETE FROM {mov_table} WHERE sec_type = $1", sec_type
        )


# ---------------------------------------------------------------------------
#  Month-batch writes (COPY both tables with allocated forecast_ids)
# ---------------------------------------------------------------------------

async def _write_month(
    conn,
    mov_table: str,
    mov_columns: list[str],
    rows: list[dict],
) -> int:
    """Write one month-batch of bucket rows to the mov table + its linked
    forecast_results rows.

    Pure COPY, NO pre-clear: a month reaches this function only when it
    is missing from the mov table (incremental) or after --force already
    deleted the sec_type's rows, so re-clearing would be pure full-scan
    overhead on the partitioned tables (no stat_month index — the PK
    leads with code). Crash safety comes from transactional atomicity
    instead: the id allocation + both COPYs run in ONE transaction, so a
    crash mid-month rolls back both tables together (no orphan
    forecast_results rows, no half-written months). forecast_ids are
    allocated per chunk from the identity sequence and mirrored into
    both tables (1:1 link); the identity column is GENERATED BY DEFAULT
    so explicit ids are accepted.
    """
    if not rows:
        return 0
    total = 0
    for i in range(0, len(rows), _WRITE_CHUNK):
        chunk = rows[i : i + _WRITE_CHUNK]
        async with conn.transaction():
            ids = [
                r[0] for r in await conn.fetch(
                    f"SELECT nextval('{_FORECAST_ID_SEQ}') "
                    f"FROM generate_series(1, $1::int)",
                    len(chunk),
                )
            ]
            for row, fid in zip(chunk, ids):
                row["forecast_id"] = fid
            mov_rows, result_rows = split_forecast_rows(chunk, mov_columns)
            # copy_insert_async opens its own inner transaction block —
            # under the outer one it becomes a savepoint, still atomic.
            await copy_insert_async(conn, TABLE_FORECAST, result_rows)
            await copy_insert_async(conn, mov_table, mov_rows)
        total += len(chunk)
    return total


# ---------------------------------------------------------------------------
#  Per-sec_type pipeline
# ---------------------------------------------------------------------------

async def _process_sec_type(
    conn,
    sec_type: str,
    specs: list[MonthSpec],
    *,
    force: bool,
) -> tuple[int, int]:
    """Process one sec_type end-to-end. Returns (mov_rsi, mov_std) rows written."""
    print(f"\n  [{sec_type}] Fetching active codes...", flush=True)
    codes = sorted(await fetch_active_codes(conn, sec_type))
    print(f"  [{sec_type}]   {len(codes):,} active codes", flush=True)
    if not codes:
        print(f"  [{sec_type}]   no active codes; skipping.", flush=True)
        return 0, 0

    # ---- Emittable-month bound -------------------------------------------
    # The full-window gate (below) means a snapshot month can emit rows
    # only once the universe's EARLIEST first-data date precedes the
    # month's window start (≈ first data + WINDOW_YEARS). Without this
    # bound the earlier months are "missing" FOREVER (they can never
    # emit a row), so every incremental run re-targets them and drags
    # the input fetch back years before any code needs it.
    first_dates = await fetch_first_dates(conn, sec_type, codes)
    if first_dates:
        f_min = min(first_dates.values())
        n_all = len(specs)
        specs = [
            s for s in specs
            if _shift_years(s.stat_month, -WINDOW_YEARS)
            + timedelta(days=1) > f_min
        ]
        print(f"  [{sec_type}]   universe first data {f_min.isoformat()} "
              f"→ {len(specs)} of {n_all} months can emit "
              f"(first data + {WINDOW_YEARS}y full-window gate)",
              flush=True)

    # ---- Determine target months (incremental / force) -------------------
    if force:
        print(f"  [{sec_type}] FORCE mode: deleting existing {sec_type} "
              f"mov rows + linked forecast_results...", flush=True)
        await _delete_sec_type(conn, sec_type)
        missing_rsi, missing_std = list(specs), list(specs)
    else:
        missing_rsi = await _missing_stat_months(conn, TABLE_MOV_RSI,
                                                 sec_type, specs)
        missing_std = await _missing_stat_months(conn, TABLE_MOV_STD,
                                                 sec_type, specs)
        print(f"  [{sec_type}]   missing months: rsi={len(missing_rsi)} "
              f"std={len(missing_std)} of {len(specs)}", flush=True)
    if not missing_rsi and not missing_std:
        print(f"  [{sec_type}]   up to date; skipping.", flush=True)
        return 0, 0

    # ---- Fetch inputs (bounded to the earliest needed window start) ------
    todo = {s.stat_month: s for s in missing_rsi + missing_std}
    since = min(s.lower for s in todo.values())
    print(f"  [{sec_type}] Fetching joined inputs (price / high / low / "
          f"ma / rsi / std) for {len(codes):,} codes since "
          f"{since.isoformat()}...", flush=True)
    df = await fetch_analysis_inputs(conn, sec_type, codes, since)
    print(f"  [{sec_type}]   {len(df):,} (code, date) rows", flush=True)
    if df.empty:
        print(f"  [{sec_type}]   no source data; skipping.", flush=True)
        return 0, 0
    episodes = await fetch_hyped_episodes(conn, sec_type, since)
    print(f"  [{sec_type}]   {len(episodes):,} market-hype episodes",
          flush=True)

    # ---- Wide grid + shared change matrices -------------------------------
    df = add_forward_changes(df)
    grid_ord, grid_codes, didx, cidx = build_grid(df)
    shape = (len(grid_ord), len(grid_codes))
    chg = build_change_matrices(df, shape, didx, cidx)
    hype = build_hype_matrix(episodes, grid_ord, grid_codes, shape)
    # Per-code first data date as ABSOLUTE epoch ordinals (min(date)
    # from the DB — fetched above for the emittable-month bound; the
    # fetched frame is bounded to the earliest window start and would
    # clip long-history codes). DATE-space gate: codes enter a month
    # only once their own history spans the FULL trailing 5-year window
    # (first listed 2020-01 → first snapshot 2025-01).
    first_ord = first_ords_from_dates(first_dates, grid_codes)
    print(f"  [{sec_type}]   {int(hype.sum()):,} hyped (date, code) "
          f"grid cells", flush=True)

    windows_by_month = {
        w.stat_month: w for w in month_row_windows(grid_ord, specs)
    }
    windows_rsi = [
        windows_by_month[m] for m in
        (s.stat_month for s in missing_rsi) if m in windows_by_month
    ]
    windows_std = [
        windows_by_month[m] for m in
        (s.stat_month for s in missing_std) if m in windows_by_month
    ]

    n_rsi = n_std = 0

    # ---- Stage 1: RSI extreme buckets -------------------------------------
    if windows_rsi:
        print(f"  [{sec_type}] Computing RSI extreme buckets "
              f"(windows={list(RSI_WINDOWS)}) for {len(windows_rsi)} "
              f"months...", flush=True)
        rsi_mats = {
            f"rsi_{w}": scatter_column(df, f"rsi_{w}days", shape, didx, cidx)
            for w in RSI_WINDOWS
        }
        for stat_month, rows in compute_rsi_results(
            rsi_mats, chg, windows_rsi, grid_codes, sec_type, hype,
            first_ord,
        ):
            n = await _write_month(conn, TABLE_MOV_RSI, MOV_RSI_COLUMNS, rows)
            n_rsi += n
            print(f"    [{stat_month}] mov_rsi + forecast_results: "
                  f"wrote {n:,} rows", flush=True)
        del rsi_mats

    # ---- Stage 2: Bollinger-breach buckets --------------------------------
    if windows_std:
        print(f"  [{sec_type}] Computing Bollinger-breach buckets "
              f"(ma_windows={list(MA_WINDOWS)}) for {len(windows_std)} "
              f"months...", flush=True)
        std_mats: dict = {
            "price": scatter_column(df, "price", shape, didx, cidx),
            "high": scatter_column(df, "high", shape, didx, cidx),
            "low": scatter_column(df, "low", shape, didx, cidx),
        }
        for w in MA_WINDOWS:
            std_mats[f"ma_{w}"] = scatter_column(df, f"ma_{w}days", shape,
                                                 didx, cidx)
            std_mats[f"std_{w}"] = scatter_column(df, f"std_{w}days", shape,
                                                  didx, cidx)
        for stat_month, rows in compute_std_results(
            std_mats, chg, windows_std, grid_codes, sec_type, hype,
            first_ord,
        ):
            n = await _write_month(conn, TABLE_MOV_STD, MOV_STD_COLUMNS, rows)
            n_std += n
            print(f"    [{stat_month}] mov_std + forecast_results: "
                  f"wrote {n:,} rows", flush=True)
        del std_mats

    return n_rsi, n_std


# ---------------------------------------------------------------------------
#  Main
# ---------------------------------------------------------------------------

async def main() -> None:
    ap = argparse.ArgumentParser(
        description="Analysis Forecasts (ETF + Index + Stock). Monthly "
                    "per-security forecast analysis over a trailing "
                    "5-year window: analysis_forecasts.mov_rsi (RSI "
                    "extreme-percentile buckets) and mov_std "
                    "(Bollinger-breach buckets) hold the motivation "
                    "cols; forecast_results (linked 1:1 via forecast_id) "
                    "holds the result data — mean forward changes at "
                    "next/5d/20d/60d horizons; close-based max/min "
                    "forward changes and the within-window close "
                    "swing amplitude (max_low_change_ratio) at the "
                    "5d/20d/60d "
                    "horizons; per-horizon >1% reversal probabilities."
    )
    ap.add_argument(
        "--sec-type", choices=SEC_TYPES, default=None,
        help="Process only this sec_type (for testing). Default: all.",
    )
    ap.add_argument(
        "--months", type=int, default=N_MONTHS,
        help=f"Number of completed month-end snapshots to target "
             f"(default {N_MONTHS} = 5 years, monthly).",
    )
    add_force_arg(ap)
    args = ap.parse_args()
    force = args.force

    sec_types = (args.sec_type,) if args.sec_type else SEC_TYPES
    specs = build_month_specs(n_months=args.months)

    t0 = time.time()
    print_build_header(
        "ANALYZE FORECASTS (monthly RSI-extreme + Bollinger-breach "
        "forecasts)",
        tables=f"{TABLE_FORECAST}, {TABLE_MOV_RSI}, {TABLE_MOV_STD}",
        sec_types=", ".join(sec_types),
        months=f"{args.months} (window {specs[0].lower} .. "
               f"{specs[-1].stat_month})",
        mode="FORCE (delete + recompute all target months)" if force
        else "incremental (missing stat_months only)",
    )

    conn = await get_db_connection_async()
    try:
        total_rsi = total_std = 0
        for st in sec_types:
            r, s = await _process_sec_type(conn, st, specs, force=force)
            total_rsi += r
            total_std += s

            if r or force:
                await upsert_analysis_identity(
                    conn, name=ANALYSIS_NAME_RSI,
                    detail_name=ANALYSIS_NAME_RSI, description=DESCRIPTION_RSI,
                )
            if s or force:
                await upsert_analysis_identity(
                    conn, name=ANALYSIS_NAME_STD,
                    detail_name=ANALYSIS_NAME_STD, description=DESCRIPTION_STD,
                )

        if total_rsi == 0 and total_std == 0 and not force:
            print("\n  DB is up to date; nothing to do.", flush=True)
            print_wall_time(t0)
            return

        print(f"\n  TOTAL: {total_rsi:,} mov_rsi rows + "
              f"{total_std:,} mov_std rows written (with linked "
              f"forecast_results rows)", flush=True)
        print_wall_time(t0)
    finally:
        try:
            await asyncio.wait_for(conn.close(), timeout=10)
        except (asyncio.TimeoutError, Exception):
            pass


if __name__ == "__main__":
    from _common.post_check import post_check
    try:
        asyncio.run(main())
    finally:
        post_check()
