"""Snapshot-batch writer for analyze.analysis_forecasts: forecast_id
allocation, the three-table snapshot transaction, incremental
snapshot detection + refresh/force deletions (annual grid)."""
from __future__ import annotations

import logging
from datetime import date

import numpy as np

from _common.db_commons import (
    _chunk_keys_by_weight,
    chunked_dml_by_key_async,
    copy_insert_async,
    csv_copy_from_frame_async,
    DEFAULT_MAX_REPLICA_LAG_MB,
    _wait_for_replica_lag_async,
)
from _common.df_utils import host_array

from analyze.analysis_forecasts.config import (
    LOOKBACK_PERIOD,
    REGIME_WEIGHTS_TABLE,
    RESULT_COLUMNS,
    TABLE_BASE_RATE,
    TABLE_DIVIDEND,
    TABLE_FORECAST,
    TABLE_HIGH_LOW_STREAKS,
    TABLE_IDENTITIES,
    TABLE_MARGIN_RATIO,
    TABLE_MOV_PAIRS,
    TABLE_MOV_PAIRS_EMA,
    TABLE_MOV_RSI,
    TABLE_MOV_STD,
    TABLE_PE,
    TRIGGER_DELAY_MAX,
    mutable_dates,
)
from analyze.analysis_forecasts.wide import StatSpec

logger = logging.getLogger(__name__)

# Max period rows per COPY chunk (a full stock-universe snapshot of rsi
# buckets is <= 64 × ~5,400 ≈ 345K buckets → 1.38M period rows; chunk
# 100K period rows = 25K buckets per chunk).
_WRITE_CHUNK = 100_000

# Identity sequence backing forecast_results.forecast_id (GENERATED BY
# DEFAULT AS IDENTITY → <table>_<column>_seq). Allocated one per
# bucket (NOT per period row), shared across all 4 periods.
_FORECAST_ID_SEQ = "analysis_forecasts.forecast_results_forecast_id_seq"


# ---------------------------------------------------------------------------
#  forecast_identities registry rows (one per bucket, shared PK identity)
# ---------------------------------------------------------------------------

def _identity_rows(bucket_rows: list[dict], mov_table: str) -> list[dict]:
    """One forecast_identities registry row per bucket — the shared
    identity (sec_type, code, stat_date; NOT stored on the motivation
    tables anymore — this registry is the only place it lives), tagged
    with the bucket family (the motivation table's short name), the
    bucket's mean streak length (streak_signal_days — the 2026-09
    streak semantics: the multi-day streak families mov_rsi / mov_std /
    pe_state / dividend_state record the MEAN run length of their merged
    incremental-anchor signals, mov_pairs / mov_pairs_ema the 1-day constant,
    margin_ratio a constant 1, high_low_streaks its config
    mean_day_count) and the mean trigger delay (delayed_signal_days —
    the mean trading-day offset of the bucket's emitted trigger anchors
    within their streaks, capped at 5; 0 for
    1-day signals). Both INTEGER whole days. Reads the UNFILTERED bucket
    payload dicts (the mov-table projection drops the identity +
    streak_signal_days / delayed_signal_days fields)."""
    bucket = mov_table.split(".")[-1]
    return [
        {
            "forecast_id": m["forecast_id"],
            "sec_type": m["sec_type"],
            "code": m["code"],
            "stat_date": m["stat_date"],
            "bucket": bucket,
            "streak_signal_days": m.get("streak_signal_days"),
            "delayed_signal_days": m.get("delayed_signal_days", 0),
            "lookback_period": m.get("lookback_period", LOOKBACK_PERIOD),
        }
        for m in bucket_rows
    ]


# ---------------------------------------------------------------------------
#  Incremental snapshot detection + refresh-window deletion
# ---------------------------------------------------------------------------

async def _compute_dates(
    conn,
    table: str,
    sec_type: str,
    specs: list[StatSpec],
) -> tuple[list[StatSpec], list[date]]:
    """(compute, refreshed) — the spec snapshots to (re)compute for
    ``table`` / sec_type.

    compute = stat_dates MISSING from the table plus the PRESENT
    snapshots inside the MUTABLE SCOPE (config.mutable_dates — the
    ROLLING LATEST snapshot, always, plus the newest completed year-end
    while its 20-trading-day forward windows are still unrealized).
    A year-end snapshot written right after New Year carries truncated
    20d occurrence counts — its forward windows were not complete yet
    at write time — so present mutable snapshots are deleted and
    recomputed on every run (the caller performs the deletion). Truly
    missing snapshots need no delete. Completed year-ends outside the
    mutable scope are ALL-HISTORY: present ones are never recomputed
    (the --force path rebuilds them explicitly).

    Present snapshots are read from the forecast_identities registry
    (bucket-filtered) — the motivation tables carry no identity
    columns anymore; base_rates is not registered there (no
    forecast_id), so it is read directly.

    Returns the compute list (spec order) and the refreshed snapshots'
    dates (empty when nothing present needs a refresh).
    """
    if table == TABLE_BASE_RATE:
        rows = await conn.fetch(
            f"SELECT DISTINCT stat_date FROM {table} WHERE sec_type = $1",
            sec_type,
        )
    else:
        rows = await conn.fetch(
            f"SELECT DISTINCT stat_date FROM {TABLE_IDENTITIES} "
            f"WHERE sec_type = $1 AND bucket = $2",
            sec_type, table.split(".")[-1],
        )
    present: set[date] = {r["stat_date"] for r in rows}
    refresh_set = mutable_dates(present, date.today())
    refreshed = [
        s.stat_date for s in specs
        if s.stat_date in present and s.stat_date in refresh_set
    ]
    compute = [
        s for s in specs
        if s.stat_date not in present or s.stat_date in refresh_set
    ]
    return compute, refreshed


# Buckets (identity rows) per delete chunk: the results fan out
# ~4-period x <=6-delay per bucket (~34 rows/bucket on the wide
# families), so a 3,000-bucket chunk deletes ~100K result rows per
# COMMIT — the commit-chunk target.
_DELETE_BUCKET_TARGET = 3_000


async def _delete_linked_buckets(
    conn,
    table: str,
    sec_type: str,
    stat_dates: list[date] | None,
    *,
    codes: list[str] | None = None,
) -> None:
    """Delete the given stat_dates' linked trio (forecast_results + the
    mov ``table`` + the forecast_identities registry rows) CHUNKED BY
    PARTITION KEY.

    Why id-sets rather than the old join-delete: ``forecast_id`` is the
    results table's PARTITION KEY, so ``DELETE ... WHERE forecast_id =
    ANY($1::bigint[])`` resolves through the per-partition forecast_id
    indexes — no USING-join re-scan per chunk (a join cannot prune the
    hash partitions and would re-pay a full scan per 100K-row chunk).
    The doomed (code, forecast_id) pairs come from ONE indexed registry
    scan; codes accumulate into ~_DELETE_BUCKET_TARGET-bucket chunks
    (whole codes, never split — the bulk-write rule: a multi-million-
    row single-statement DELETE retains all its WAL behind one
    transaction and the replication slot cannot advance until it
    commits), the three deletes of a chunk share ONE transaction (a
    code's results + motivation + registry rows vanish atomically, the
    registry rows last), and the replica-lag cap pauses between chunks.

    ``codes`` (the --codes scope) restricts every delete to the given
    codes — None (default) deletes the whole sec_type scope, so the
    recompute that follows must cover every active code."""
    scope = "i.sec_type = $1 AND i.bucket = $2"
    params: list = [sec_type, table.split(".")[-1]]
    if stat_dates is not None:
        scope += " AND i.stat_date = ANY($3::date[])"
        params.append(stat_dates)
    if codes is not None:
        scope += f" AND i.code = ANY(${len(params) + 1}::text[])"
        params.append(codes)
    rows = await conn.fetch(
        f"SELECT i.code, i.forecast_id FROM {TABLE_IDENTITIES} i "
        f"WHERE {scope}",
        *params,
    )
    if not rows:
        return
    ids_by_code: dict[str, list[int]] = {}
    for r in rows:
        ids_by_code.setdefault(r["code"], []).append(r["forecast_id"])
    weighted = [(c, len(v)) for c, v in ids_by_code.items()]
    for chunk in _chunk_keys_by_weight(weighted, _DELETE_BUCKET_TARGET):
        # Between commit chunks (no transaction open, no locks): wait
        # out standby replay lag before generating more WAL.
        await _wait_for_replica_lag_async(conn, DEFAULT_MAX_REPLICA_LAG_MB)
        chunk_ids = [fid for c in chunk for fid in ids_by_code[c]]
        async with conn.transaction():
            # The delete is by the PARTITION-KEY id set — an index-
            # resolvable point workload — but the planner's ANY-array
            # row estimate (~millions) makes it prefer a seq scan over
            # all 16 hash partitions (~60s+ per chunk measured). The
            # per-partition pkey/forecast_id indexes resolve the chunk
            # in milliseconds; force index scans for THIS statement
            # class only (SET LOCAL — transaction-scoped).
            await conn.execute("SET LOCAL enable_seqscan = off")
            await conn.execute(
                f"DELETE FROM {TABLE_FORECAST} "
                f"WHERE forecast_id = ANY($1::bigint[])",
                chunk_ids,
            )
            await conn.execute(
                f"DELETE FROM {table} WHERE forecast_id = ANY($1::bigint[])",
                chunk_ids,
            )
            # the registry rows go LAST — the scope was resolved
            # through them before the transaction opened
            await conn.execute(
                f"DELETE FROM {TABLE_IDENTITIES} "
                f"WHERE forecast_id = ANY($1::bigint[])",
                chunk_ids,
            )


async def _delete_dates(
    conn,
    table: str,
    sec_type: str,
    months: list[date],  # snapshot stat_dates
    *,
    linked_results: bool,
    codes: list[str] | None = None,
) -> None:
    """Delete the given stat_dates' rows of ``table`` (sec_type-scoped)
    — plus, for the forecast_id-linked tables, the forecast_results AND
    forecast_identities rows they link to (base_rates has no link).
    The linked deletes resolve (sec_type, bucket, stat_date) through
    the forecast_identities registry — the motivation tables carry no
    identity columns anymore. ``codes`` (the --codes scope) restricts
    every delete to the given codes — None (default) deletes the whole
    sec_type scope, so the recompute that follows must cover every
    active code. See _delete_linked_buckets for the chunking contract
    (partition-key chunks, ~100K result rows per COMMIT)."""
    if not months:
        return
    if linked_results:
        await _delete_linked_buckets(
            conn, table, sec_type, months, codes=codes,
        )
    else:
        # base_rates: per-code doomed-row counts -> code chunks (the
        # PK index (sec_type, code, stat_date) makes each chunk's
        # delete an index scan)
        weight_sql = (
            f"SELECT code, count(*) AS n FROM {table} "
            f"WHERE sec_type = $1 AND stat_date = ANY($2::date[])"
        )
        params: list = [sec_type, months]
        if codes is not None:
            weight_sql += " AND code = ANY($3::text[])"
            params.append(codes)
        weight_rows = await conn.fetch(weight_sql, *params)
        await chunked_dml_by_key_async(
            conn,
            statements=[(
                f"DELETE FROM {table} "
                f"WHERE sec_type = $1 AND stat_date = ANY($2::date[])",
                " AND code = ANY(${ph}::text[])",
            )],
            params=tuple(params),
            weighted_keys=[(r["code"], r["n"]) for r in weight_rows],
        )


# ---------------------------------------------------------------------------
#  Stale-key sweep (the rolling latest key's predecessor + legacy keys)
# ---------------------------------------------------------------------------

async def _sweep_stale_dates(
    conn,
    sec_type: str,
    grid_dates: set[date],
    *,
    metrics: set[str] | None = None,
    codes: list[str] | None = None,
) -> None:
    """Delete the sec_type's scoped rows whose stat_date is NOT on the
    current snapshot grid — the retired ROLLING LATEST keys (yesterday's
    key once today's has taken over; on the first run after the
    rolling-key migration, the legacy year-end-keyed running snapshot).

    The registry read is metrics/codes-scoped exactly like the deletes
    that follow, so a scoped run never judges another scope's rows.
    regime_weights (per stat_date, no forecast_id) is swept from its
    own table; base_rates (not registered in the identities) likewise.
    Runs BEFORE the target resolution — stale keys must neither be
    recomputed nor suppress anything."""
    # registry-resolved families: ONE scoped read, per-bucket stale sets
    linked_tables = [t for t in _STAGE_OF_TABLE if t != TABLE_BASE_RATE]
    if metrics is not None:
        linked_tables = [t for t in linked_tables
                         if _STAGE_OF_TABLE[t] in metrics]
    table_of_bucket = {t.split(".")[-1]: t for t in linked_tables}

    rows: list = []
    if metrics is None:
        # unscoped: every bucket's keys are in scope
        code_clause = "" if codes is None else " AND code = ANY($2::text[])"
        params = (sec_type,) if codes is None else (sec_type, codes)
        rows = await conn.fetch(
            f"SELECT DISTINCT bucket, stat_date FROM {TABLE_IDENTITIES} "
            f"WHERE sec_type = $1{code_clause}", *params,
        )
    elif table_of_bucket:
        # metrics-scoped: only the selected families' keys are read, so
        # another scope's rows are never judged (a stage set without
        # registry-resolved families — e.g. base-only — skips the read)
        code_clause = "" if codes is None else " AND code = ANY($3::text[])"
        params = (sec_type, list(table_of_bucket))
        if codes is not None:
            params += (codes,)
        rows = await conn.fetch(
            f"SELECT DISTINCT bucket, stat_date FROM {TABLE_IDENTITIES} "
            f"WHERE sec_type = $1 AND bucket = ANY($2::text[]){code_clause}",
            *params,
        )

    stale_by_bucket: dict[str, list[date]] = {}
    for r in rows:
        if r["stat_date"] not in grid_dates:
            stale_by_bucket.setdefault(r["bucket"], []).append(r["stat_date"])
    for bucket, stale in stale_by_bucket.items():
        await _delete_dates(conn, table_of_bucket[bucket], sec_type,
                            sorted(set(stale)), linked_results=True,
                            codes=codes)

    # base_rates (no forecast_id) and regime_weights (no forecast_id)
    # sweep straight off their own tables.
    for table in (TABLE_BASE_RATE, REGIME_WEIGHTS_TABLE):
        if codes is None:
            rows = await conn.fetch(
                f"SELECT DISTINCT stat_date FROM {table} "
                f"WHERE sec_type = $1", sec_type,
            )
            stale = sorted({r["stat_date"] for r in rows} - grid_dates)
            if stale:
                await conn.execute(
                    f"DELETE FROM {table} WHERE sec_type = $1 "
                    f"AND stat_date = ANY($2::date[])", sec_type, stale,
                )
        else:
            rows = await conn.fetch(
                f"SELECT DISTINCT stat_date FROM {table} "
                f"WHERE sec_type = $1 AND code = ANY($2::text[])",
                sec_type, codes,
            )
            stale = sorted({r["stat_date"] for r in rows} - grid_dates)
            if stale:
                await conn.execute(
                    f"DELETE FROM {table} WHERE sec_type = $1 "
                    f"AND stat_date = ANY($2::date[]) "
                    f"AND code = ANY($3::text[])",
                    sec_type, stale, codes,
                )


# ---------------------------------------------------------------------------
#  Force deletion (mov rows + their linked forecast_results rows)
# ---------------------------------------------------------------------------

# Target table → --only stage key (the per-metric stage filter; a
# filtered force run deletes ONLY the selected families' rows).
_STAGE_OF_TABLE: dict[str, str] = {
    TABLE_MOV_RSI: "rsi",
    TABLE_MOV_STD: "std",
    TABLE_MOV_PAIRS: "pairs",
    TABLE_MOV_PAIRS_EMA: "epairs",
    TABLE_HIGH_LOW_STREAKS: "hstreaks",
    TABLE_MARGIN_RATIO: "mratio",
    TABLE_PE: "pe",
    TABLE_DIVIDEND: "div",
    TABLE_BASE_RATE: "base",
}


async def _delete_sec_type(conn, sec_type: str, metrics: set[str] | None = None,
                           codes: list[str] | None = None) -> None:
    """Delete a sec_type's mov_* / margin_ratio_state /
    pe_state / dividend_state / high_low_streaks rows, the
    forecast_results + forecast_identities rows they link to, and its
    base_rates rows. Identity-keyed deletes resolve through the
    forecast_identities registry. ``metrics`` (the --forecast-metrics
    stage keys) restricts the deletion to the selected families — None
    (default) deletes every family. ``codes`` (the --codes scope)
    restricts the deletion to the given codes — None (default) deletes
    the whole sec_type scope, so the recompute that follows must cover
    every active code. Chunked per _delete_linked_buckets (a whole-
    sec_type stock purge reaches ~50M result rows — per-code forecast_id
    chunks keep every COMMIT's WAL bounded)."""
    for table, linked in ((TABLE_MOV_RSI, True), (TABLE_MOV_STD, True),
                          (TABLE_MOV_PAIRS, True),
                          (TABLE_MOV_PAIRS_EMA, True),
                          (TABLE_HIGH_LOW_STREAKS, True),
                          (TABLE_MARGIN_RATIO, True),
                          (TABLE_PE, True),
                          (TABLE_DIVIDEND, True),
                          (TABLE_BASE_RATE, False)):
        if metrics is not None and _STAGE_OF_TABLE[table] not in metrics:
            continue
        if linked:
            # stat_dates=None = the family's whole registry scope
            await _delete_linked_buckets(
                conn, table, sec_type, None, codes=codes,
            )
        else:
            weight_sql = (
                f"SELECT code, count(*) AS n FROM {table} "
                f"WHERE sec_type = $1"
            )
            params: list = [sec_type]
            if codes is not None:
                weight_sql += " AND code = ANY($2::text[])"
                params.append(codes)
            weight_rows = await conn.fetch(weight_sql, *params)
            await chunked_dml_by_key_async(
                conn,
                statements=[(
                    f"DELETE FROM {table} WHERE sec_type = $1",
                    " AND code = ANY(${ph}::text[])",
                )],
                params=tuple(params),
                weighted_keys=[(r["code"], r["n"]) for r in weight_rows],
            )


# ---------------------------------------------------------------------------
#  Month-batch writes (COPY both tables with allocated forecast_ids)
# ---------------------------------------------------------------------------

# The float result columns (the CSV NULL-sweep targets — see
# _write_snapshot): the max/min legs carry ±inf aggregation sentinels on
# all-invalid groups.
_FLOAT_RESULT_COLUMNS = ("ave_change", "std_change", "max_change",
                         "min_change", "ave_close")


def _py_scalars(records: list[dict]) -> list[dict]:
    """Frame-derived dicts → plain python scalars for the binary COPY
    (np.int64 is not an int; np.datetime64 → python date)."""
    for r in records:
        for k, v in r.items():
            if isinstance(v, np.datetime64):
                r[k] = v.astype("datetime64[D]").astype(object)
            elif v is not None and hasattr(v, "item"):
                r[k] = v.item()
    return records


async def _write_snapshot(
    conn,
    mov_table: str,
    mov_columns: list[str],
    payload,
    *,
    max_replica_lag_mb: float | None = DEFAULT_MAX_REPLICA_LAG_MB,
) -> int:
    """Write one snapshot-batch of bucket rows to the mov table + its linked
    forecast_results rows + the forecast_identities registry rows.

    ``payload`` is a bucket-major result FRAME from the df-engine
    families — consecutive runs of equal ``_bkt`` share one bucket, 4
    period rows each (the engine stamped the shared constants as
    columns and the ragged arrays as PostgreSQL array-literal TEXT;
    the legacy list-of-dicts shape of the retired opp_pair numpy
    pipeline was removed with that family).

    forecast_results streams via the CSV COPY path
    (``csv_copy_from_frame_async`` — whole-column host rendering; the
    binary per-value records path measured ~3x slower at index scale);
    the mov + identity tables are small bucket-first projections and
    stay on the binary dict path. One transaction per ~_WRITE_CHUNK-row
    span group; pure COPY, NO pre-clear — crash safety comes from
    transactional atomicity. Between chunk transactions the writer
    pauses while a streaming standby's replay lag exceeds
    ``max_replica_lag_mb`` (4096 MB default, None disables) so bulk
    loads cannot outrun the replica into slot-retained WAL.

    Returns the number of BUCKETS written (R, not 4·R).
    """
    if payload is None or len(payload) == 0:
        return 0
    frame = payload

    bkt = np.asarray(
        host_array(frame["_bkt"].to_numpy()), dtype="int64",
    )
    # Bucket spans: consecutive runs of equal _bkt.
    spans: list[tuple[int, int]] = []
    start, cur = 0, bkt[0]
    for i in range(1, len(bkt)):
        if bkt[i] != cur:
            spans.append((start, i))
            start, cur = i, bkt[i]
    spans.append((start, len(bkt)))
    # The delay-ladder invariant (the 2026-09-21 incremental-anchor
    # regression guard): within every bucket span the delay column is
    # contiguous 0..max and capped at TRIGGER_DELAY_MAX — delay d
    # exists iff the run reached day d, so a gap or a missing 0 means
    # the run detection broke.
    delays = np.asarray(
        host_array(frame["delay"].to_numpy()), dtype="int64",
    )
    at_bucket_start = np.zeros(len(delays), dtype=bool)
    at_bucket_start[[s for s, _ in spans]] = True
    prev_delay = np.empty(len(delays), dtype="int64")
    prev_delay[0] = -1
    prev_delay[1:] = delays[:-1]
    # Rows arrive bucket-major, delay-ascending with the 4 period rows
    # (next/5d/20d/mixed) repeating each delay — so WITHIN a bucket a
    # delay change must step exactly +1 (repeats are the period
    # fan-out), each bucket must open at delay 0, and no rung exceeds
    # the cap. Bucket starts are exempt from the +1 step (their
    # predecessor row is another bucket's last row).
    new_delay_run = (~at_bucket_start) & (delays != prev_delay)
    ok = ~new_delay_run | (delays - prev_delay == 1)
    ok &= (delays >= 0) & (delays <= TRIGGER_DELAY_MAX)
    ok[at_bucket_start] &= delays[at_bucket_start] == 0
    if not ok.all():
        bad_idx = np.nonzero(~ok)[0]
        # FULL spans of the first bad buckets — the delay pattern of the
        # whole bucket is what diagnoses a contiguity break.
        bad_bkts = np.unique(frame.iloc[bad_idx]["_bkt"].to_numpy())[:3]
        keep_idx = np.nonzero(np.isin(bkt, bad_bkts))[0]
        dump = frame.iloc[keep_idx]
        try:
            dump.to_csv("temp_scripts/delay_violations.csv", index=False)
        except Exception:
            pass
        bad_codes = frame.iloc[bad_idx[:5]]["code"].tolist()
        raise ValueError(
            f"delay-ladder invariant violated in {mov_table} snapshot "
            f"batch: {len(bad_idx)} rows whose bucket's delay column "
            f"is not contiguous 0..max(≤{TRIGGER_DELAY_MAX}) — first "
            f"bad buckets {bad_codes} (dumped context to "
            f"temp_scripts/delay_violations.csv)"
        )
    # Pack whole bucket spans into ~_WRITE_CHUNK-row COPY chunks.
    chunk_spans: list[list[tuple[int, int]]] = [[]]
    n_chunk = 0
    for span in spans:
        if n_chunk and n_chunk + (span[1] - span[0]) > _WRITE_CHUNK:
            chunk_spans.append([])
            n_chunk = 0
        chunk_spans[-1].append(span)
        n_chunk += span[1] - span[0]
    n_total_buckets = 0
    for spans_part in chunk_spans:
        n_buckets = len(spans_part)
        # Between-chunk throttle: each chunk commits its own transaction,
        # so pausing here lets the standby's replay position (and the
        # replication slot's WAL bound) advance before more WAL is
        # generated. No-op while lag is within the cap.
        if max_replica_lag_mb is not None:
            await _wait_for_replica_lag_async(conn, max_replica_lag_mb)
        # The chunk's spans are contiguous (packed in order) — one iloc
        # slice carries exactly its rows; ids assign CHUNK-LOCALLY.
        lo, hi = spans_part[0][0], spans_part[-1][1]
        chunk_frame = frame.iloc[lo:hi]
        lens = np.asarray([e - s for s, e in spans_part], dtype="int64")
        rel_starts = np.asarray(
            [s - lo for s, _ in spans_part], dtype="int64",
        )
        async with conn.transaction():
            ids = [
                r[0] for r in await conn.fetch(
                    f"SELECT nextval('{_FORECAST_ID_SEQ}') "
                    f"FROM generate_series(1, $1::int)",
                    n_buckets,
                )
            ]
            # One forecast_id per bucket group, shared across its rows.
            chunk_frame = chunk_frame.assign(
                forecast_id=np.repeat(np.asarray(ids, dtype="int64"), lens),
            )
            # ±inf → NaN on the float result columns: to_csv renders
            # literal 'inf', which NUMERIC rejects (the old dict
            # boundary's _NONFINITE → None mapping).
            for col in _FLOAT_RESULT_COLUMNS:
                s = chunk_frame[col]
                chunk_frame[col] = s.where(np.isfinite(s))
            await csv_copy_from_frame_async(
                conn, TABLE_FORECAST, chunk_frame, columns=RESULT_COLUMNS,
            )
            # The mov + identity rows read the FIRST row of each bucket
            # group (the projections drop the period / result columns;
            # the registry projection keeps the streak / delay means).
            firsts = _py_scalars(
                chunk_frame.take(rel_starts).to_dict("records")
            )
            identity_rows = _identity_rows(firsts, mov_table)
            await copy_insert_async(conn, TABLE_IDENTITIES, identity_rows)
            await copy_insert_async(
                conn, mov_table,
                [{k: r[k] for k in mov_columns} for r in firsts],
            )
        n_total_buckets += n_buckets
    return n_total_buckets
