"""Month-batch writer for analyze.analysis_forecasts: forecast_id
allocation, the three-table month transaction, incremental month
detection + refresh/force deletions."""
from __future__ import annotations

import logging
from datetime import date

import numpy as np
import pandas as pd

from _common.db_commons import copy_insert_async, csv_copy_from_frame_async
from _common.df_utils import host_array

from analyze.analysis_forecasts.config import (
    ALL_PERIODS,
    LOOKBACK_PERIOD,
    RESULT_COLUMNS,
    REFRESH_MONTHS,
    TABLE_BASE_RATE,
    TABLE_DIVIDEND,
    TABLE_FORECAST,
    TABLE_HIGH_LOW_STREAKS,
    TABLE_IDENTITIES,
    TABLE_MARGIN_RATIO,
    TABLE_MOV_PAIRS,
    TABLE_MOV_PAIRS_EMA,
    TABLE_MOV_RSI,
    TABLE_MOV_STD,
    TABLE_OPP_PAIR,
    TABLE_PE,
    TABLE_PX_VOL,
    TRIGGER_DELAY_MAX,
)
from analyze.analysis_forecasts.wide import MonthSpec

logger = logging.getLogger(__name__)

# Max period rows per COPY chunk (a full stock-universe month of rsi
# buckets is <= 64 × ~5,400 ≈ 345K buckets → 1.38M period rows; chunk
# 100K period rows = 25K buckets per chunk).
_WRITE_CHUNK = 100_000

# Identity sequence backing forecast_results.forecast_id (GENERATED BY
# DEFAULT AS IDENTITY → <table>_<column>_seq). Allocated one per
# bucket (NOT per period row), shared across all 4 periods.
_FORECAST_ID_SEQ = "analysis_forecasts.forecast_results_forecast_id_seq"


# ---------------------------------------------------------------------------
#  forecast_identities registry rows (one per bucket, shared PK identity)
# ---------------------------------------------------------------------------

def _identity_rows(bucket_rows: list[dict], mov_table: str) -> list[dict]:
    """One forecast_identities registry row per bucket — the shared
    identity (sec_type, code, stat_month; NOT stored on the motivation
    tables anymore — this registry is the only place it lives), tagged
    with the bucket family (the motivation table's short name), the
    bucket's mean streak length (streak_signal_days — the 2026-09
    streak semantics: the multi-day streak families mov_rsi / mov_std /
    px_vol_state record the MEAN run length of their merged
    incremental-anchor signals, mov_pairs / mov_pairs_ema the 1-day constant,
    margin_ratio / opp_pair a constant 1, high_low_streaks its config
    mean_day_count) and the mean trigger delay (delayed_signal_days —
    the mean trading-day offset of the bucket's emitted trigger anchors
    within their streaks, capped at 5; 0 for
    1-day signals). Both INTEGER whole days. Reads the UNFILTERED bucket
    payload dicts (the mov-table projection drops the identity +
    streak_signal_days / delayed_signal_days fields).
    opp_pair_state is the only family whose subject column is not
    ``code``: its rows register the DROPPING industry_id (the
    forecast-target pair_industry_id stays on the motivation row)."""
    bucket = mov_table.split(".")[-1]
    return [
        {
            "forecast_id": m["forecast_id"],
            "sec_type": m["sec_type"],
            "code": m.get("code", m.get("industry_id")),
            "stat_month": m["stat_month"],
            "bucket": bucket,
            "streak_signal_days": m.get("streak_signal_days"),
            "delayed_signal_days": m.get("delayed_signal_days", 0),
            "lookback_period": m.get("lookback_period", LOOKBACK_PERIOD),
        }
        for m in bucket_rows
    ]


# ---------------------------------------------------------------------------
#  Incremental month detection + refresh-window deletion
# ---------------------------------------------------------------------------

async def _compute_months(
    conn,
    table: str,
    sec_type: str,
    specs: list[MonthSpec],
) -> tuple[list[MonthSpec], list[date]]:
    """(compute, refreshed) — the spec months to (re)compute for
    ``table`` / sec_type.

    compute = stat_months MISSING from the table plus the PRESENT
    months inside the refresh window (the RUNNING month — always the
    newest spec — plus the most recent REFRESH_MONTHS - 1 completed
    months). A month written right after month-end carries
    permanently truncated 20d occurrence counts — its forward
    windows were not complete yet at write time — so present
    refresh-window months are deleted and recomputed on every run
    (the caller performs the deletion). Truly missing months need no
    delete.

    Present months are read from the forecast_identities registry
    (bucket-filtered) — the motivation tables carry no identity
    columns anymore; base_rates is not registered there (no
    forecast_id), so it is read directly.

    Returns the compute list (spec order) and the refreshed months'
    dates (empty when nothing present needs a refresh).
    """
    if table == TABLE_BASE_RATE:
        rows = await conn.fetch(
            f"SELECT DISTINCT stat_month FROM {table} WHERE sec_type = $1",
            sec_type,
        )
    else:
        rows = await conn.fetch(
            f"SELECT DISTINCT stat_month FROM {TABLE_IDENTITIES} "
            f"WHERE sec_type = $1 AND bucket = $2",
            sec_type, table.split(".")[-1],
        )
    present: set[date] = {r["stat_month"] for r in rows}
    refresh_set = {s.stat_month for s in specs[-REFRESH_MONTHS:]}
    refreshed = [
        s.stat_month for s in specs
        if s.stat_month in present and s.stat_month in refresh_set
    ]
    compute = [
        s for s in specs
        if s.stat_month not in present or s.stat_month in refresh_set
    ]
    return compute, refreshed


async def _delete_months(
    conn,
    table: str,
    sec_type: str,
    months: list[date],
    *,
    linked_results: bool,
) -> None:
    """Delete the given stat_months' rows of ``table`` (sec_type-scoped)
    — plus, for the forecast_id-linked tables, the forecast_results AND
    forecast_identities rows they link to (base_rates has no link).
    The linked deletes resolve (sec_type, bucket, stat_month) through
    the forecast_identities registry — the motivation tables carry no
    identity columns anymore."""
    if not months:
        return
    if linked_results:
        bucket = table.split(".")[-1]
        # opp_pair_state plays industry_id in the code role (its
        # partition key); every other family's column is code
        code_col = "industry_id" if table == TABLE_OPP_PAIR else "code"
        await conn.execute(
            f"DELETE FROM {TABLE_FORECAST} f USING {TABLE_IDENTITIES} i "
            f"WHERE i.forecast_id = f.forecast_id AND i.sec_type = $1 "
            f"AND i.bucket = $2 AND i.stat_month = ANY($3::date[])",
            sec_type, bucket, months,
        )
        await conn.execute(
            f"DELETE FROM {table} m USING {TABLE_IDENTITIES} i "
            f"WHERE m.forecast_id = i.forecast_id "
            f"AND m.{code_col} = i.code AND i.sec_type = $1 "
            f"AND i.bucket = $2 AND i.stat_month = ANY($3::date[])",
            sec_type, bucket, months,
        )
        # the registry rows go LAST — the two deletes above resolve
        # (sec_type, bucket, stat_month) through them
        await conn.execute(
            f"DELETE FROM {TABLE_IDENTITIES} i "
            f"WHERE i.sec_type = $1 AND i.bucket = $2 "
            f"AND i.stat_month = ANY($3::date[])",
            sec_type, bucket, months,
        )
    else:
        await conn.execute(
            f"DELETE FROM {table} WHERE sec_type = $1 "
            f"AND stat_month = ANY($2::date[])",
            sec_type, months,
        )


# ---------------------------------------------------------------------------
#  Force deletion (mov rows + their linked forecast_results rows)
# ---------------------------------------------------------------------------

# Target table → --only stage key (the per-metric stage filter; a
# filtered force run deletes ONLY the selected families' rows).
_STAGE_OF_TABLE: dict[str, str] = {
    TABLE_MOV_RSI: "rsi",
    TABLE_MOV_STD: "std",
    TABLE_MOV_PAIRS: "pairs",
    TABLE_MOV_PAIRS_EMA: "epairs",
    TABLE_HIGH_LOW_STREAKS: "hstreaks",
    TABLE_PX_VOL: "pxvol",
    TABLE_MARGIN_RATIO: "mratio",
    TABLE_PE: "pe",
    TABLE_DIVIDEND: "div",
    TABLE_BASE_RATE: "base",
}


async def _delete_sec_type(conn, sec_type: str, metrics: set[str] | None = None) -> None:
    """Delete a sec_type's mov_* / px_vol_state / margin_ratio_state /
    pe_state / dividend_state / high_low_streaks rows, the
    forecast_results + forecast_identities rows they link to, and its
    base_rates rows. Identity-keyed deletes resolve through the
    forecast_identities registry. ``only`` (the --only stage keys)
    restricts the deletion to the selected families — None (default)
    deletes every family."""
    for table, linked in ((TABLE_MOV_RSI, True), (TABLE_MOV_STD, True),
                          (TABLE_MOV_PAIRS, True),
                          (TABLE_MOV_PAIRS_EMA, True),
                          (TABLE_HIGH_LOW_STREAKS, True),
                          (TABLE_PX_VOL, True),
                          (TABLE_MARGIN_RATIO, True),
                          (TABLE_PE, True),
                          (TABLE_DIVIDEND, True),
                          (TABLE_BASE_RATE, False)):
        if metrics is not None and _STAGE_OF_TABLE[table] not in metrics:
            continue
        if linked:
            bucket = table.split(".")[-1]
            # opp_pair_state plays industry_id in the code role (its
            # partition key); every other family's column is code
            code_col = ("industry_id" if table == TABLE_OPP_PAIR
                        else "code")
            await conn.execute(
                f"DELETE FROM {TABLE_FORECAST} f USING {TABLE_IDENTITIES} i "
                f"WHERE i.forecast_id = f.forecast_id "
                f"AND i.sec_type = $1 AND i.bucket = $2",
                sec_type, bucket,
            )
            await conn.execute(
                f"DELETE FROM {table} m USING {TABLE_IDENTITIES} i "
                f"WHERE m.forecast_id = i.forecast_id "
                f"AND m.{code_col} = i.code "
                f"AND i.sec_type = $1 AND i.bucket = $2",
                sec_type, bucket,
            )
            # the registry rows go LAST — the two deletes above resolve
            # (sec_type, bucket) through them
            await conn.execute(
                f"DELETE FROM {TABLE_IDENTITIES} i "
                f"WHERE i.sec_type = $1 AND i.bucket = $2",
                sec_type, bucket,
            )
        else:
            await conn.execute(
                f"DELETE FROM {table} WHERE sec_type = $1", sec_type
            )


# ---------------------------------------------------------------------------
#  Month-batch writes (COPY both tables with allocated forecast_ids)
# ---------------------------------------------------------------------------

_ARRAY_COLUMNS = ("trigger_dates", "streak_starts", "streak_ends",
                  "streak_days", "trigger_excess")

# The float result columns (the CSV NULL-sweep targets — see
# _write_month): the max/min legs carry ±inf aggregation sentinels on
# all-invalid groups.
_FLOAT_RESULT_COLUMNS = ("ave_change", "std_change", "max_change",
                         "min_change", "reverse_prob", "threshold")


def _pg_array_lit(v) -> object:
    """One array-column value → its PostgreSQL array-literal TEXT (the
    dict path's render of what the df engine emits natively): lists
    become ``{a,b,...}`` (NULL elements for NaN/None/NaT), None stays
    None (a NULL array)."""
    if v is None:
        return None
    parts = []
    for x in v:
        if x is None:
            parts.append("NULL")
        elif isinstance(x, float):
            parts.append("NULL" if x != x else repr(x))
        elif hasattr(x, "isoformat"):          # datetime.date / datetime
            parts.append(x.isoformat())
        else:
            parts.append(str(x))
    return "{" + ",".join(parts) + "}"


def _py_scalars(records: list[dict]) -> list[dict]:
    """Frame-derived dicts → plain python scalars for the binary COPY
    (np.int64 is not an int; np.datetime64 → python date)."""
    for r in records:
        for k, v in r.items():
            if isinstance(v, np.datetime64):
                r[k] = v.astype("datetime64[D]").astype(object)
            elif v is not None and hasattr(v, "item"):
                r[k] = v.item()
    return records


async def _write_month(
    conn,
    mov_table: str,
    mov_columns: list[str],
    payload,
) -> int:
    """Write one month-batch of bucket rows to the mov table + its linked
    forecast_results rows + the forecast_identities registry rows.

    ``payload`` is bucket-major — consecutive runs of equal ``_bkt``
    share one bucket, 4 period rows each. Two shapes reach here:

      - a result FRAME from the df-engine families (the fast path: the
        engine stamped the shared constants as columns and the ragged
        arrays as PostgreSQL array-literal TEXT);
      - a list of row DICTS from the legacy numpy pipeline (opp_pair) —
        normalized to the same frame shape here (arrays literalized,
        ``_bkt`` stamped by the 4-period stride).

    forecast_results streams via the CSV COPY path
    (``csv_copy_from_frame_async`` — whole-column host rendering; the
    binary per-value records path measured ~3x slower at index scale);
    the mov + identity tables are small bucket-first projections and
    stay on the binary dict path. One transaction per ~_WRITE_CHUNK-row
    span group; pure COPY, NO pre-clear — crash safety comes from
    transactional atomicity.

    Returns the number of BUCKETS written (R, not 4·R).
    """
    if isinstance(payload, list):
        if not payload:
            return 0
        real_pd = getattr(pd, "_fsproxy_slow", pd)
        stride = len(ALL_PERIODS)
        rows = payload
        for i, r in enumerate(rows):
            r["_bkt"] = i // stride
            for col in _ARRAY_COLUMNS:
                if col in r:
                    r[col] = _pg_array_lit(r[col])
        frame = real_pd.DataFrame(rows)
    else:
        frame = payload
        if frame is None or len(frame) == 0:
            return 0

    bkt = np.asarray(
        host_array(frame["_bkt"].to_numpy()), dtype="int64",
    )
    # Bucket spans: consecutive runs of equal _bkt.
    spans: list[tuple[int, int]] = []
    start, cur = 0, bkt[0]
    for i in range(1, len(bkt)):
        if bkt[i] != cur:
            spans.append((start, i))
            start, cur = i, bkt[i]
    spans.append((start, len(bkt)))
    # The delay-ladder invariant (the 2026-09-21 incremental-anchor
    # regression guard): within every bucket span the delay column is
    # contiguous 0..max and capped at TRIGGER_DELAY_MAX — delay d
    # exists iff the run reached day d, so a gap or a missing 0 means
    # the run detection broke. (The legacy dict path — opp_pair — is
    # delay-0 only and trivially satisfies it.)
    delays = np.asarray(
        host_array(frame["delay"].to_numpy()), dtype="int64",
    )
    at_bucket_start = np.zeros(len(delays), dtype=bool)
    at_bucket_start[[s for s, _ in spans]] = True
    prev_delay = np.empty(len(delays), dtype="int64")
    prev_delay[0] = -1
    prev_delay[1:] = delays[:-1]
    # Rows arrive bucket-major, delay-ascending with the 4 period rows
    # (next/5d/20d/mixed) repeating each delay — so WITHIN a bucket a
    # delay change must step exactly +1 (repeats are the period
    # fan-out), each bucket must open at delay 0, and no rung exceeds
    # the cap. Bucket starts are exempt from the +1 step (their
    # predecessor row is another bucket's last row).
    new_delay_run = (~at_bucket_start) & (delays != prev_delay)
    ok = ~new_delay_run | (delays - prev_delay == 1)
    ok &= (delays >= 0) & (delays <= TRIGGER_DELAY_MAX)
    ok[at_bucket_start] &= delays[at_bucket_start] == 0
    if not ok.all():
        bad_idx = np.nonzero(~ok)[0]
        # FULL spans of the first bad buckets — the delay pattern of the
        # whole bucket is what diagnoses a contiguity break.
        bad_bkts = np.unique(frame.iloc[bad_idx]["_bkt"].to_numpy())[:3]
        keep_idx = np.nonzero(np.isin(bkt, bad_bkts))[0]
        dump = frame.iloc[keep_idx]
        try:
            dump.to_csv("temp_scripts/delay_violations.csv", index=False)
        except Exception:
            pass
        bad_codes = frame.iloc[bad_idx[:5]]["code"].tolist()
        raise ValueError(
            f"delay-ladder invariant violated in {mov_table} month "
            f"batch: {len(bad_idx)} rows whose bucket's delay column "
            f"is not contiguous 0..max(≤{TRIGGER_DELAY_MAX}) — first "
            f"bad buckets {bad_codes} (dumped context to "
            f"temp_scripts/delay_violations.csv)"
        )
    # Pack whole bucket spans into ~_WRITE_CHUNK-row COPY chunks.
    chunk_spans: list[list[tuple[int, int]]] = [[]]
    n_chunk = 0
    for span in spans:
        if n_chunk and n_chunk + (span[1] - span[0]) > _WRITE_CHUNK:
            chunk_spans.append([])
            n_chunk = 0
        chunk_spans[-1].append(span)
        n_chunk += span[1] - span[0]
    n_total_buckets = 0
    for spans_part in chunk_spans:
        n_buckets = len(spans_part)
        # The chunk's spans are contiguous (packed in order) — one iloc
        # slice carries exactly its rows; ids assign CHUNK-LOCALLY.
        lo, hi = spans_part[0][0], spans_part[-1][1]
        chunk_frame = frame.iloc[lo:hi]
        lens = np.asarray([e - s for s, e in spans_part], dtype="int64")
        rel_starts = np.asarray(
            [s - lo for s, _ in spans_part], dtype="int64",
        )
        async with conn.transaction():
            ids = [
                r[0] for r in await conn.fetch(
                    f"SELECT nextval('{_FORECAST_ID_SEQ}') "
                    f"FROM generate_series(1, $1::int)",
                    n_buckets,
                )
            ]
            # One forecast_id per bucket group, shared across its rows.
            chunk_frame = chunk_frame.assign(
                forecast_id=np.repeat(np.asarray(ids, dtype="int64"), lens),
            )
            # ±inf → NaN on the float result columns: to_csv renders
            # literal 'inf', which NUMERIC rejects (the old dict
            # boundary's _NONFINITE → None mapping).
            for col in _FLOAT_RESULT_COLUMNS:
                s = chunk_frame[col]
                chunk_frame[col] = s.where(np.isfinite(s))
            await csv_copy_from_frame_async(
                conn, TABLE_FORECAST, chunk_frame, columns=RESULT_COLUMNS,
            )
            # The mov + identity rows read the FIRST row of each bucket
            # group (the projections drop the period / result columns;
            # the registry projection keeps the streak / delay means).
            firsts = _py_scalars(
                chunk_frame.take(rel_starts).to_dict("records")
            )
            identity_rows = _identity_rows(firsts, mov_table)
            await copy_insert_async(conn, TABLE_IDENTITIES, identity_rows)
            await copy_insert_async(
                conn, mov_table,
                [{k: r[k] for k in mov_columns} for r in firsts],
            )
        n_total_buckets += n_buckets
    return n_total_buckets
