"""Month-batch writer for analyze.analysis_forecasts: forecast_id
allocation, the three-table month transaction, incremental month
detection + refresh/force deletions."""
from __future__ import annotations

import logging
from datetime import date

from _common.db_commons import copy_insert_async

from analyze.analysis_forecasts.config import (
    ALL_PERIODS,
    LOOKBACK_PERIOD,
    REFRESH_MONTHS,
    TABLE_BASE_RATE,
    TABLE_DIVIDEND,
    TABLE_FORECAST,
    TABLE_HIGH_LOW_STREAKS,
    TABLE_IDENTITIES,
    TABLE_MARGIN_RATIO,
    TABLE_MOV_GAP,
    TABLE_MOV_PAIRS,
    TABLE_MOV_PAIRS_EMA,
    TABLE_MOV_RSI,
    TABLE_MOV_STD,
    TABLE_OPP_PAIR,
    TABLE_PE,
    TABLE_PX_VOL,
)
from analyze.analysis_forecasts.wide import MonthSpec, split_forecast_rows

logger = logging.getLogger(__name__)

# Max period rows per COPY chunk (a full stock-universe month of rsi
# buckets is <= 64 × ~5,400 ≈ 345K buckets → 1.38M period rows; chunk
# 100K period rows = 25K buckets per chunk).
_WRITE_CHUNK = 100_000

# Each forecast bucket expands to 5 period rows (next / 5d / 20d / 60d
# plus the weight-blended 'mixed' row).
_PERIODS = len(ALL_PERIODS)

# Identity sequence backing forecast_results.forecast_id (GENERATED BY
# DEFAULT AS IDENTITY → <table>_<column>_seq). Allocated one per
# bucket (NOT per period row), shared across all 4 periods.
_FORECAST_ID_SEQ = "analysis_forecasts.forecast_results_forecast_id_seq"


# ---------------------------------------------------------------------------
#  forecast_identities registry rows (one per bucket, shared PK identity)
# ---------------------------------------------------------------------------

def _identity_rows(bucket_rows: list[dict], mov_table: str) -> list[dict]:
    """One forecast_identities registry row per bucket — the shared
    identity (sec_type, code, stat_month; NOT stored on the motivation
    tables anymore — this registry is the only place it lives), tagged
    with the bucket family (the motivation table's short name) and the
    bucket's mean streak length (streak_signal_days — the 2026-09
    streak semantics: the multi-day streak families mov_rsi / mov_std /
    mov_gap / px_vol_state record the MEAN run length of their merged
    mid-anchored signals, mov_pairs / mov_pairs_ema the 1-day constant,
    margin_ratio / opp_pair a constant 1, high_low_streaks its config
    mean_day_count). Reads the UNFILTERED bucket payload dicts (the
    mov-table projection drops the identity + streak_signal_days
    fields). opp_pair_state is the only family whose subject column is
    not ``code``: its rows register the DROPPING industry_id (the
    forecast-target pair_industry_id stays on the motivation row)."""
    bucket = mov_table.split(".")[-1]
    return [
        {
            "forecast_id": m["forecast_id"],
            "sec_type": m["sec_type"],
            "code": m.get("code", m.get("industry_id")),
            "stat_month": m["stat_month"],
            "bucket": bucket,
            "streak_signal_days": m.get("streak_signal_days"),
            "lookback_period": m.get("lookback_period", LOOKBACK_PERIOD),
        }
        for m in bucket_rows
    ]


# ---------------------------------------------------------------------------
#  Incremental month detection + refresh-window deletion
# ---------------------------------------------------------------------------

async def _compute_months(
    conn,
    table: str,
    sec_type: str,
    specs: list[MonthSpec],
) -> tuple[list[MonthSpec], list[date]]:
    """(compute, refreshed) — the spec months to (re)compute for
    ``table`` / sec_type.

    compute = stat_months MISSING from the table plus the PRESENT
    months inside the refresh window (the most recent REFRESH_MONTHS
    completed months). A month written right after month-end carries
    permanently truncated 20d/60d occurrence counts — its forward
    windows were not complete yet at write time — so present
    refresh-window months are deleted and recomputed on every run
    (the caller performs the deletion). Truly missing months need no
    delete.

    Present months are read from the forecast_identities registry
    (bucket-filtered) — the motivation tables carry no identity
    columns anymore; base_rates is not registered there (no
    forecast_id), so it is read directly.

    Returns the compute list (spec order) and the refreshed months'
    dates (empty when nothing present needs a refresh).
    """
    if table == TABLE_BASE_RATE:
        rows = await conn.fetch(
            f"SELECT DISTINCT stat_month FROM {table} WHERE sec_type = $1",
            sec_type,
        )
    else:
        rows = await conn.fetch(
            f"SELECT DISTINCT stat_month FROM {TABLE_IDENTITIES} "
            f"WHERE sec_type = $1 AND bucket = $2",
            sec_type, table.split(".")[-1],
        )
    present: set[date] = {r["stat_month"] for r in rows}
    refresh_set = {s.stat_month for s in specs[-REFRESH_MONTHS:]}
    refreshed = [
        s.stat_month for s in specs
        if s.stat_month in present and s.stat_month in refresh_set
    ]
    compute = [
        s for s in specs
        if s.stat_month not in present or s.stat_month in refresh_set
    ]
    return compute, refreshed


async def _delete_months(
    conn,
    table: str,
    sec_type: str,
    months: list[date],
    *,
    linked_results: bool,
) -> None:
    """Delete the given stat_months' rows of ``table`` (sec_type-scoped)
    — plus, for the forecast_id-linked tables, the forecast_results AND
    forecast_identities rows they link to (base_rates has no link).
    The linked deletes resolve (sec_type, bucket, stat_month) through
    the forecast_identities registry — the motivation tables carry no
    identity columns anymore."""
    if not months:
        return
    if linked_results:
        bucket = table.split(".")[-1]
        # opp_pair_state plays industry_id in the code role (its
        # partition key); every other family's column is code
        code_col = "industry_id" if table == TABLE_OPP_PAIR else "code"
        await conn.execute(
            f"DELETE FROM {TABLE_FORECAST} f USING {TABLE_IDENTITIES} i "
            f"WHERE i.forecast_id = f.forecast_id AND i.sec_type = $1 "
            f"AND i.bucket = $2 AND i.stat_month = ANY($3::date[])",
            sec_type, bucket, months,
        )
        await conn.execute(
            f"DELETE FROM {table} m USING {TABLE_IDENTITIES} i "
            f"WHERE m.forecast_id = i.forecast_id "
            f"AND m.{code_col} = i.code AND i.sec_type = $1 "
            f"AND i.bucket = $2 AND i.stat_month = ANY($3::date[])",
            sec_type, bucket, months,
        )
        # the registry rows go LAST — the two deletes above resolve
        # (sec_type, bucket, stat_month) through them
        await conn.execute(
            f"DELETE FROM {TABLE_IDENTITIES} i "
            f"WHERE i.sec_type = $1 AND i.bucket = $2 "
            f"AND i.stat_month = ANY($3::date[])",
            sec_type, bucket, months,
        )
    else:
        await conn.execute(
            f"DELETE FROM {table} WHERE sec_type = $1 "
            f"AND stat_month = ANY($2::date[])",
            sec_type, months,
        )


# ---------------------------------------------------------------------------
#  Force deletion (mov rows + their linked forecast_results rows)
# ---------------------------------------------------------------------------

# Target table → --only stage key (the per-metric stage filter; a
# filtered force run deletes ONLY the selected families' rows).
_STAGE_OF_TABLE: dict[str, str] = {
    TABLE_MOV_RSI: "rsi",
    TABLE_MOV_STD: "std",
    TABLE_MOV_GAP: "gap",
    TABLE_MOV_PAIRS: "pairs",
    TABLE_MOV_PAIRS_EMA: "epairs",
    TABLE_HIGH_LOW_STREAKS: "hstreaks",
    TABLE_PX_VOL: "pxvol",
    TABLE_MARGIN_RATIO: "mratio",
    TABLE_PE: "pe",
    TABLE_DIVIDEND: "div",
    TABLE_BASE_RATE: "base",
}


async def _delete_sec_type(conn, sec_type: str, metrics: set[str] | None = None) -> None:
    """Delete a sec_type's mov_* / px_vol_state / margin_ratio_state /
    pe_state / dividend_state / high_low_streaks rows, the
    forecast_results + forecast_identities rows they link to, and its
    base_rates rows. Identity-keyed deletes resolve through the
    forecast_identities registry. ``only`` (the --only stage keys)
    restricts the deletion to the selected families — None (default)
    deletes every family."""
    for table, linked in ((TABLE_MOV_RSI, True), (TABLE_MOV_STD, True),
                          (TABLE_MOV_GAP, True), (TABLE_MOV_PAIRS, True),
                          (TABLE_MOV_PAIRS_EMA, True),
                          (TABLE_HIGH_LOW_STREAKS, True),
                          (TABLE_PX_VOL, True),
                          (TABLE_MARGIN_RATIO, True),
                          (TABLE_PE, True),
                          (TABLE_DIVIDEND, True),
                          (TABLE_BASE_RATE, False)):
        if metrics is not None and _STAGE_OF_TABLE[table] not in metrics:
            continue
        if linked:
            bucket = table.split(".")[-1]
            # opp_pair_state plays industry_id in the code role (its
            # partition key); every other family's column is code
            code_col = ("industry_id" if table == TABLE_OPP_PAIR
                        else "code")
            await conn.execute(
                f"DELETE FROM {TABLE_FORECAST} f USING {TABLE_IDENTITIES} i "
                f"WHERE i.forecast_id = f.forecast_id "
                f"AND i.sec_type = $1 AND i.bucket = $2",
                sec_type, bucket,
            )
            await conn.execute(
                f"DELETE FROM {table} m USING {TABLE_IDENTITIES} i "
                f"WHERE m.forecast_id = i.forecast_id "
                f"AND m.{code_col} = i.code "
                f"AND i.sec_type = $1 AND i.bucket = $2",
                sec_type, bucket,
            )
            # the registry rows go LAST — the two deletes above resolve
            # (sec_type, bucket) through them
            await conn.execute(
                f"DELETE FROM {TABLE_IDENTITIES} i "
                f"WHERE i.sec_type = $1 AND i.bucket = $2",
                sec_type, bucket,
            )
        else:
            await conn.execute(
                f"DELETE FROM {table} WHERE sec_type = $1", sec_type
            )


# ---------------------------------------------------------------------------
#  Month-batch writes (COPY both tables with allocated forecast_ids)
# ---------------------------------------------------------------------------

async def _write_month(
    conn,
    mov_table: str,
    mov_columns: list[str],
    rows: list[dict],
) -> int:
    """Write one month-batch of bucket rows to the mov table + its linked
    forecast_results rows + the forecast_identities registry rows.

    ``rows`` is (4·R,) period rows emitted by ``build_result_rows`` —
    bucket-major (4 consecutive rows per bucket). Allocates R forecast_ids
    (one per bucket) and shares each across the 4 period rows, then
    splits into R mov_rows + 4·R result_rows + R identity_rows and COPYs
    all three tables in ONE transaction per chunk. Pure COPY, NO
    pre-clear. Crash safety comes from transactional atomicity.

    Returns the number of BUCKETS written (R, not 4·R).
    """
    if not rows:
        return 0
    n_total_buckets = 0
    # Chunk must be a multiple of 4 (complete bucket groups) — trim.
    chunk_size = _WRITE_CHUNK - (_WRITE_CHUNK % _PERIODS)
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i : i + chunk_size]
        n_buckets = len(chunk) // _PERIODS
        async with conn.transaction():
            ids = [
                r[0] for r in await conn.fetch(
                    f"SELECT nextval('{_FORECAST_ID_SEQ}') "
                    f"FROM generate_series(1, $1::int)",
                    n_buckets,
                )
            ]
            # Assign each forecast_id to its 4 consecutive period rows.
            for bi, fid in enumerate(ids):
                for j in range(_PERIODS):
                    chunk[bi * _PERIODS + j]["forecast_id"] = fid
            mov_rows, result_rows = split_forecast_rows(chunk, mov_columns)
            # Identity rows read the UNFILTERED first period row of each
            # bucket group (the mov-table projection drops the
            # registry-only streak_signal_days field).
            identity_rows = _identity_rows(chunk[:: _PERIODS], mov_table)
            await copy_insert_async(conn, TABLE_FORECAST, result_rows)
            await copy_insert_async(conn, TABLE_IDENTITIES, identity_rows)
            await copy_insert_async(conn, mov_table, mov_rows)
        n_total_buckets += n_buckets
    return n_total_buckets
