"""Per-family identity descriptions (analysis_identity upserts)."""

DESCRIPTION_RSI = (
    "RSI extreme-day annual-snapshot forecasts (ETF + Index + Stock). For each "
    "security and completed year-end (stat_date), over the trailing "
    "10-year window (stat_date - 10y, stat_date] of the code's own "
    "trading days: for each RSI window W (3/6/10/14/20/60, "
    "mirroring analysis.mov_ave_rsi; 120/255/500 removed) and each "
    "percentile width pct "
    "(1/5/10/25), buckets the days whose rsi_{W}days is in the TOP pct% "
    "(overbought) or BOTTOM pct% (oversold) of the window's non-NULL "
    "rsi_{W}days distribution (linear-interpolated percentile threshold), "
    "with streak-merge (since 2026-09, replacing the legacy fixed "
    "5-day cooldown): dates that keep satisfying the bucket condition "
    "CONTINUOUSLY collapse into ONE forecast signal anchored at the "
    "streak's MID day (the ((L-1)//2 + 1)-th day, the high_low_streaks "
    "convention); the bucket's mean streak length is recorded on "
    "analysis_forecasts.forecast_identities.streak_signal_days. "
    "Buckets are split by regime_state (the stats.market_regimes day "
    "label calm/hot/panic/quiet of their trigger days); "
    "result data in analysis_forecasts.forecast_results via "
    "forecast_id: mean forward fractional changes at the "
    "next-day, 5d and 20d horizons; close-based max/min forward "
    "changes "
    "at the 5d/20d horizons; plus "
    "the swing-aware probability of a REVERSAL against the bucket side beyond the fixed 1% bar (threshold column, 0.01 — the n-day forward window's ADVERSE PATH EXTREME vs ±1%: the window swung past the bar against the side at some close, not merely the period-end; path extreme < −thr for top / > +thr for bottom)"
    ". Rows are emitted only where day_count > 0 "
    "and codes join a snapshot from their own first-data date — each "
    "code's stats span its ACTUAL window (min(actual history, 10y); "
    "partial windows expected). "
    "Incremental at annual-snapshot granularity: stat_dates missing from "
    "mov_rsi are computed plus the mutable scope (the rolling latest "
    "snapshot keyed at the latest data date + the newest year-end "
    "while its 20d forward windows realize); --force "
    "deletes the sec_type's rows (mov_rsi "
    "+ linked forecast_results) and recomputes every target month."
)

DESCRIPTION_STD = (
    "Bollinger-breach annual-snapshot forecasts (ETF + Index + Stock). For each "
    "security and completed year-end (stat_date), over the trailing "
    "10-year window (stat_date - 10y, stat_date] of the code's own "
    "trading days: for each MA window W (5/20/60; 120/255 removed) and "
    "each sigma "
    "multiple k (0.5/1.0/1.5/2.0/2.5/3.0), buckets the breach days — "
    "price > ma_{W} + k*std_{W}days (side=upper) or price < "
    "ma_{W} - k*std_{W}days (side=lower), with ma_{W} from "
    "stats.*_tech_stats and std_{W}days from "
    "analysis.mov_ave_spreads_detail. Buckets are split by PK member "
    "regime_state (the stats.market_regimes day label of the "
    "breach days), with streak-merge (since "
    "2026-09, replacing the legacy fixed 5-day cooldown): dates that "
    "keep satisfying the breach condition CONTINUOUSLY collapse into "
    "ONE forecast signal anchored at the streak's MID day (the "
    "((L-1)//2 + 1)-th day, the high_low_streaks convention); the "
    "bucket's mean streak length is recorded on "
    "analysis_forecasts.forecast_identities.streak_signal_days. Result "
    "data in analysis_forecasts.forecast_results via forecast_id: mean "
    "forward fractional changes at the next-day, 5d and 20d "
    "horizons; close-based max/min forward changes at the "
    "5d/20d horizons; plus the per-horizon "
    "swing-aware probability of a REVERSAL against the breach side "
    "beyond the fixed 1% bar (threshold column, 0.01 — the "
    "n-day forward window's ADVERSE PATH EXTREME vs ±1%: the window "
    "swung past the bar against the side at some close, not merely "
    "the period-end; path extreme < −thr for upper / "
    "> +thr for lower). Rows are emitted only where day_count > 0 and only for "
    "codes with data in the snapshot's window — each code's stats span "
    "its ACTUAL window (min(actual history, 10y); partial windows "
    "expected). "
    "Incremental at annual-snapshot granularity: stat_dates missing from "
    "mov_std are computed plus the mutable scope (the rolling latest "
    "snapshot keyed at the latest data date + the newest year-end "
    "while its 20d forward windows may not have been complete at "
    "first write); --force "
    "deletes the sec_type's rows (mov_std + linked forecast_results) "
    "and recomputes every target month."
)

DESCRIPTION_BASE_RATE = (
    "Unconditional same-window base rates for the forecast analyses "
    "(RSI-extreme / Bollinger-breach buckets). Per "
    "security and completed year-end (stat_date), over the same "
    "trailing 10-year window (stat_date - 10y, stat_date] and the same "
    "price space as the buckets, but over ALL of the code's window "
    "trading days (not just the extreme days): per horizon (next/5d/"
    "20d) the mean forward fractional change (base_ave_change) "
    "and the valid-day count (base_count) — "
    "plus the weight-blended period='mixed' reference row "
    "(config.MIXED_HORIZON_WEIGHTS, the unconditional profile the bucket "
    "rows' blended mixed period is read against). "
    "Reading a bucket's ave_change against this turns it "
    "into lift. "
    "Same live gate as the mov_* tables (codes join a snapshot from "
    "their own first-data date — each code's window is its actual "
    "history, min(actual, 10y)); one row per (code, "
    "period) where base_count > 0. Incremental at annual-snapshot granularity: "
    "stat_dates missing from base_rates are computed plus the mutable "
    "scope (the rolling latest snapshot keyed at the latest data "
    "date + the newest year-end while its 20d forward windows "
    "realize); --force "
    "deletes the sec_type's rows and recomputes every target month."
)

DESCRIPTION_MARGIN_RATIO = (
    "Margin-buy intensity state annual-snapshot forecasts (ETF + Stock — index "
    "has no own margin data). For each security and completed year-end "
    "(stat_date), over the trailing 10-year window (stat_date - 10y, "
    "stat_date] of the code's own trading days, buckets the days by "
    "the 融资买入额/成交额 ratio (rz_buy / trading_amount, RONGZI only) "
    "state vs the code's own trailing distribution: z = (ratio - μ)/σ "
    "of the rolling-1220-row (min 250 non-NULL) moments shifted 1 row — "
    "no_buy (rz_buy <= 0 that day) / vlow (z <= -2) / low (-2,-1] / "
    "mid (-1,+1] / high (+1,+2] / vhigh (z > +2); undefined z → no "
    "bucket. State cells (no cooldown) split by regime_state. "
    "Crowding semantics per the 2026-09 study (trend5 rank-IC -0.040 / "
    "vol5 +0.054): high/vhigh carry side top (bearish), vlow/low/"
    "no_buy side bottom, mid side flat. Result data "
    "in analysis_forecasts.forecast_results via forecast_id: mean/std/"
    "max/min forward changes at next/5d/20d, occurrence counts. "
    "Incremental at annual-snapshot granularity (missing stat_dates + the "
    "mutable scope: the rolling latest snapshot keyed at the latest "
    "data date + the newest year-end while its 20d forward windows "
    "realize); --force deletes the sec_type's rows "
    "(margin_ratio_state + linked forecast_results) and recomputes."
)

DESCRIPTION_MOV_PAIRS = (
    "MA-pair cross (golden / death cross) annual-snapshot forecasts (ETF + "
    "Index + Stock). Built on the EXISTING relative-MA-spread columns "
    "of analysis.mov_ave_spreads_detail — the parent mov_ave_spread "
    "analysis's own spread definitions, W in 60/120/255 (no new MA "
    "computation). TWO fast legs share the family (the motivation "
    "rows' fast_leg column): 'ma5' reads ma5_vs_ma{W} = (ma5 - "
    "ma_{W}) / ma_{W}, 'price' reads price_vs_ma{W} = (price - "
    "ma_{W}) / ma_{W} (the close-price cross). For each security and "
    "completed year-end (stat_date), over the trailing 10-year "
    "window (stat_date - 10y, stat_date] of the code's own trading "
    "days, buckets the CROSS days — the days the stored spread "
    "changes sign: side=top a CROSS UP / golden cross (spread[t] > 0 "
    "and spread[t-1] <= 0, the fast leg rises through the slow MA), "
    "side=bottom a CROSS DOWN / death cross (spread[t] < 0 and "
    "spread[t-1] >= 0); NULL spreads (either leg still warming up) "
    "never trigger. ONE-DAY event signals: a cross day's predecessor "
    "sits on the other side of zero, so consecutive cross days are "
    "mutually exclusive — every cross day is its own forecast signal "
    "(streak_signal_days = 1; the legacy fixed 5-day cooldown was "
    "removed 2026-09) and the regime_state split applies. "
    "Result data in analysis_forecasts.forecast_results via "
    "forecast_id: mean forward fractional changes at the next-day, "
    "5d and 20d horizons; close-based max/min forward changes "
    "at the 5d/20d horizons; plus "
    "the per-horizon swing-aware probability of a REVERSAL against "
    "the cross side beyond the fixed 1% bar (threshold "
    "column, 0.01 — the n-day forward window's ADVERSE PATH "
    "EXTREME vs ±1%: path extreme < -thr for "
    "top / > +thr for bottom). Rows are emitted only where day_count "
    "> 0 and only for codes with data in the snapshot's window (each "
    "code's stats span its actual window — min(actual history, 10y)). "
    "Incremental at annual-snapshot granularity: stat_dates missing from "
    "mov_pairs are computed plus the mutable scope (the rolling latest "
    "snapshot keyed at the latest data date + the newest year-end "
    "while its 20d forward windows realize); --force deletes the "
    "sec_type's rows (mov_pairs + linked forecast_results) and "
    "recomputes every target month."
)

DESCRIPTION_HIGH_LOW_STREAKS = (
    "MA-Spread High/Low streak mean-mid anchor annual-snapshot forecasts (ETF + "
    "Index + Stock). Built on the EXISTING band-break excursion streaks "
    "of analysis.mov_ave_high_low_pct_streaks (the mov_ave_spread "
    "analysis's own streak table — no streak recomputation; run "
    "python -m analyze.mov_ave_spread first so the source is current). "
    "For each security and completed year-end (stat_date), over the "
    "trailing 10-year window (stat_date - 10y, stat_date] of the code's "
    "own trading days: every streak whose MEAN-MID anchor day — the "
    "((day_count-1)//2 + 1)-th trading day of the span, the floor of "
    "the mean elapsed day (an 8-day streak anchors its 4th day) — "
    "falls in the window contributes that ONE day as the bucket's "
    "trigger (side top an ABOVE-band excursion: the unrounded close on "
    "end_date above the end month's high_val band; side bottom a "
    "BELOW-band excursion: below low_val — the streaks step's own "
    "test, ties to the nearer band). The anchor is EX-POST (the streak "
    "length is known only after the streak closes — an audit of "
    "streak-period behaviour, not a live trigger). No cooldown (one "
    "trigger per streak; streaks are inherently separated by a 6+-day "
    "in-band gap or a side switch). Buckets are split by regime_state "
    "(ANY ANCHOR date inside one of the code's "
    "(the stats.market_regimes day label). Result data in "
    "analysis_forecasts.forecast_results via forecast_id: mean/std/max/"
    "min forward changes from the ANCHOR day's close at the next/5d/20d "
    "horizons, occurrence counts, trigger_dates. The config "
    "JSONB records the bucket's streak-length context (mean/min/max "
    "day_count). Rows are emitted only where occurrence_count > 0 and "
    "only for codes with data in the snapshot's window (each code's "
    "stats span its actual window — min(actual history, 10y)). "
    "Incremental at annual-snapshot granularity: stat_dates missing from "
    "high_low_streaks are computed plus the mutable scope (the rolling latest "
    "snapshot keyed at the latest data date + the newest year-end "
    "while its 20d forward windows realize); --force deletes the sec_type's "
    "rows (high_low_streaks + linked forecast_results) and recomputes "
    "every target month."
)

DESCRIPTION_MOV_PAIRS_EMA = (
    "EMA-pair cross (golden / death cross) annual-snapshot forecasts (ETF + "
    "Index + Stock) — the EMA sibling of the mov_pairs family. Built "
    "on the EXISTING relative-EMA-spread columns of "
    "analysis.mov_ave_spreads_detail_ema — the parent mov_ave_spread "
    "analysis's own EMA spread definitions, W in 60/120/255 (no new "
    "EMA computation). TWO fast legs share the family (the motivation "
    "rows' fast_leg column): 'ema6' reads ema6_vs_ema{W} = (ema6 - "
    "ema_{W}) / ema_{W}, 'price' reads price_vs_ema{W} = (price - "
    "ema_{W}) / ema_{W} (the close-price cross). For each security "
    "and completed year-end (stat_date), over the trailing 10-year "
    "window (stat_date - 10y, stat_date] of the code's own trading "
    "days, buckets the CROSS days — the days the stored spread "
    "changes sign: side=top a CROSS UP / golden cross (spread[t] > 0 "
    "and spread[t-1] <= 0, the fast leg rises through the slow EMA), "
    "side=bottom a CROSS DOWN / death cross (spread[t] < 0 and "
    "spread[t-1] >= 0); NULL spreads (either leg still warming up) "
    "never trigger. ONE-DAY event signals exactly like mov_pairs: a "
    "cross day's predecessor sits on the other side of zero, so "
    "consecutive cross days are mutually exclusive — every cross day "
    "is its own forecast signal (streak_signal_days = 1; the legacy "
    "fixed 5-day cooldown was removed 2026-09) and the "
    "regime_state split applies. "
    "Result data in analysis_forecasts.forecast_results via "
    "forecast_id: mean forward fractional changes at the next-day, "
    "5d and 20d horizons; close-based max/min forward changes "
    "at the 5d/20d horizons; plus "
    "the per-horizon swing-aware probability of a REVERSAL against "
    "the cross side beyond the fixed 1% bar (threshold "
    "column, 0.01 — the n-day forward window's ADVERSE PATH "
    "EXTREME vs ±1%: path extreme < -thr for "
    "top / > +thr for bottom). Rows are emitted only where day_count "
    "> 0 and only for codes with data in the snapshot's window (each "
    "code's stats span its actual window — min(actual history, 10y)). "
    "Incremental at annual-snapshot granularity: stat_dates missing from "
    "mov_pairs_ema are computed plus the mutable scope (the rolling latest "
    "snapshot keyed at the latest data date + the newest year-end "
    "while its 20d forward windows realize); --force deletes the "
    "sec_type's rows (mov_pairs_ema + linked forecast_results) and "
    "recomputes every target month."
)

DESCRIPTION_PE = (
    "Valuation extreme-percentile annual-snapshot forecasts over the PE series "
    "of analysis.pe (ETF + Index + Stock — raw PE: index PE from "
    "stats.index_valuation.pe, etf/stock PE pre-computed by builds; "
    "NULL on no-earnings / invalid-PE days → no bucket there). For "
    "each security and completed year-end (stat_date), over the "
    "trailing 10-year window (stat_date - 10y, stat_date] of the "
    "code's own trading days, buckets the days whose pe sits in the "
    "top pct% or bottom pct% of the window's non-NULL pe values (the "
    "code's OWN distribution, linearly-interpolated quantile bars — "
    "the mov_rsi pct convention; pct ∈ {1, 5, 10, 25}; only extreme "
    "days form buckets). Qualifying runs are STREAK-MERGED (the 2026-09 "
    "unified pipeline, mov_rsi convention): consecutive days in the "
    "same bucket collapse into ONE forecast signal anchored at the "
    "run's MID day, the bucket's mean streak length recorded on "
    "forecast_identities.streak_signal_days; buckets are split by "
    "regime_state. SIDE — pe is LOWER-the-better: the top-pct% "
    "(expensive) days carry side top (bearish) and the bottom-pct% "
    "(cheap) days side bottom. Result data in "
    "analysis_forecasts.forecast_results via forecast_id: mean/std/"
    "max/min forward changes at next/5d/20d, occurrence counts, "
    "and each signal's trigger "
    "excess (the mid day's pe minus the bucket's quantile bar). "
    "Incremental at annual-snapshot granularity (missing stat_dates + the "
    "mutable scope: the rolling latest snapshot keyed at the latest "
    "data date + the newest year-end while its 20d forward windows "
    "realize); --force deletes the sec_type's rows "
    "(pe_state + linked forecast_results) and recomputes."
)

DESCRIPTION_DIVIDEND = (
    "Valuation extreme-percentile annual-snapshot forecasts over the "
    "dividend-yield series of analysis.dividends (ETF + Index + Stock "
    "— trailing-12m D/P, fractional; NULL for non-payers → only "
    "paying codes form dividend buckets). For each security and "
    "completed year-end (stat_date), over the trailing 10-year "
    "window (stat_date - 10y, stat_date] of the code's own trading "
    "days, buckets the days whose yield sits in the top pct% or "
    "bottom pct% of the window's non-NULL yield values (the code's "
    "OWN distribution, linearly-interpolated quantile bars — the "
    "mov_rsi pct convention; pct ∈ {1, 5, 10, 25}; only extreme days "
    "form buckets). Qualifying runs are STREAK-MERGED (the 2026-09 "
    "unified pipeline, mov_rsi convention): consecutive days in the "
    "same bucket collapse into ONE forecast signal anchored at the "
    "run's MID day, the bucket's mean streak length recorded on "
    "forecast_identities.streak_signal_days; buckets are split by "
    "regime_state. SIDE — the yield is HIGHER-the-better, the "
    "REVERSE of the pe family's mapping: the top-pct% (cheap, "
    "well-supported) days carry side bottom (bullish) and the "
    "bottom-pct% days side top (bearish). Result data in "
    "analysis_forecasts.forecast_results via forecast_id: mean/std/"
    "max/min forward changes at next/5d/20d, occurrence counts, "
    "and each signal's trigger "
    "excess (the mid day's yield minus the bucket's quantile bar). "
    "Incremental at annual-snapshot granularity (missing stat_dates + the "
    "mutable scope: the rolling latest snapshot keyed at the latest "
    "data date + the newest year-end while its 20d forward windows "
    "realize); --force deletes the sec_type's rows "
    "(dividend_state + linked forecast_results) and recomputes."
)
