-- ============================================================================
--  Schema: analysis_forecasts
--
--  Monthly per-security FORECAST (forecast) analysis: one row per
--  (sec_type, code, stat_month, bucket) where stat_month is a completed
--  calendar month-end DATE. Each bucket summarizes a TRAILING 5-YEAR
--  window (stat_month - 5 years, stat_month] of daily data for that
--  security — i.e. a monthly snapshot of how the security's own extreme
--  days (RSI percentiles / Bollinger breaches) behaved over the window
--  and what the forward changes after those days looked like.
--
--  Layout (motivation / result split):
--    - 01_forecast_results.sql — analysis_forecasts.forecast_results:
--      the RESULT data only (mean / high / low forward changes for
--      next, 5d, 20d, 60d horizons + per-horizon >1% reversal
--      probabilities), keyed by the surrogate forecast_id.
--    - 02_mov_rsi_mov_std.sql — analysis_forecasts.mov_rsi and
--      analysis_forecasts.mov_std: the MOTIVATION (bucket-defining)
--      columns. Each motivation row carries a forecast_id that links to
--      its forecast_results row (1:1, indexed, NOT NULL).
--    - 03_mov_gap.sql — analysis_forecasts.mov_gap: a third motivation
--      table (N-day price-return extreme-percentile buckets).
--    - 04_base_rates.sql — analysis_forecasts.base_rates: the
--      UNCONDITIONAL same-window base rates (mean forward change +
--      P(<-1%) / P(>+1%) over all window days) the bucket results are
--      read against.
--
--  Population convention:
--    - `python -m analyze.analysis_forecasts` computes one snapshot per
--      completed month, incrementally (stat_months missing from the
--      mov_* / base_rates tables are computed; the most recent
--      REFRESH_MONTHS snapshots are refreshed each run — the
--      forward-change RESULT half needs post-month-end prices that do
--      not all exist yet when a month is first written, so its
--      long-horizon occurrence counts fill in only on refresh).
--    - `--force` deletes the sec_type's mov_* rows (and their
--      forecast_results rows) and recomputes every target stat_month.
--    - Rows are emitted ONLY where the bucket day-count > 0 (empty
--      buckets — e.g. a code with no valid RSI in the window — have
--      no row in either table).
--
--  Change semantics (shared by all horizons):
--    next (1d) change    = (close[t+1] - close[t]) / close[t]
--    5d/20d/60d change   = (close[t+N] - close[t]) / close[t]
--    (signed fractional ratios, e.g. 0.05 = +5%; computed per code on
--    its own trading-day sequence — calendar gaps do not count as rows)
--
--    reverse change      = the move AGAINST the bucket's extreme side
--      beyond the bucket's adaptive reverse_threshold (k_n · σ of the
--      code's window n-day forward changes; legacy fixed 1% fallback —
--      see 01_forecast_results.sql):
--      top / upper (overbought / above upper band): change <
--      −reverse_threshold counts as a reversal;
--      bottom / lower (oversold / below lower band): change >
--      +reverse_threshold counts as a reversal.
--    reverse_prob_{n}    = P(n-day change is a reverse change beyond
--                          the row's reverse_threshold) over bucket
--                          days with a valid n-day change.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS analysis_forecasts;

COMMENT ON SCHEMA analysis_forecasts IS 'Monthly per-security forecast analysis: motivation tables (mov_rsi / mov_std) hold the extreme-day bucket definitions per (sec_type, code, stat_month, bucket); forecast_results holds the forward-change result data keyed by forecast_id (1:1 with each motivation row). Each row summarizes a trailing 5-year window of daily data. Populated incrementally by python -m analyze.analysis_forecasts.';
